### ISSUE TITLE
I want to know how to use this project on Armbian (ubuntu 16.04 LTS based).

### ISSUE THREAD

**Issue by ghost** [yangosoft/cocos2d-x-arm-opengles#1]
I compiled and run new cocos2d-3.15.1 cpp project on Armbian finally. It's fps is 30, half of standard.
I try to use opengles from linux-desktop project, so that make fps high.
I'm interested in your project but don't know how to use this.
Please help me, Thanks.

**Comment by yangosoft** [comment]
I'm so sorry but currently I'm not working on this anymore. I would suggest to use the cocos forum https://discuss.cocos2d-x.org/ the are plenty of developers there.
